i forgot a comment character
The file /dev/shm/run_00.jl could not be loaded. Please report this error!

Go back

Error message:

ArgumentError: Malformed UUID string: "45ce7b9c:7066:11ec:29b0:13acfccc64a9"
Stacktrace:
  [1] parse
    @ ./uuid.jl:83 [inlined]
  [2] UUID
    @ ./uuid.jl:87 [inlined]
  [3] load_notebook_nobackup(io::IOStream, path::String)
    @ Pluto ~/.julia/packages/Pluto/xIB4x/src/notebook/Notebook.jl:206
  [4] #53
    @ ~/.julia/packages/Pluto/xIB4x/src/notebook/Notebook.jl:288 [inlined]
  [5] open(::Pluto.var"#53#54"{String}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
  [6] open
    @ ./io.jl:328 [inlined]
  [7] load_notebook_nobackup(path::String)
    @ Pluto ~/.julia/packages/Pluto/xIB4x/src/notebook/Notebook.jl:287
  [8] load_notebook(path::String; disable_writing_notebook_files::Bool)
    @ Pluto ~/.julia/packages/Pluto/xIB4x/src/notebook/Notebook.jl:304
  [9] open(session::Pluto.ServerSession, path::String; run_async::Bool, compiler_options::Nothing, as_sample::Bool, notebook_id::Base.UUID)
    @ Pluto.SessionActions ~/.julia/packages/Pluto/xIB4x/src/webserver/SessionActions.jl:42
 [10] (::Pluto.var"#try_launch_notebook_response#280"{Pluto.var"#try_launch_notebook_response#257#281"{Pluto.ServerSession}})(action::typeof(Pluto.SessionActions.open), path_or_url::String; title::String, advice::String, home_url::String, as_redirect::Bool, action_kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:as_sample,), Tuple{Bool}}})
    @ Pluto ~/.julia/packages/Pluto/xIB4x/src/webserver/Static.jl:172
 [11] (::Pluto.var"#259#283"{Pluto.ServerSession})(request::HTTP.Messages.Request)
    @ Pluto ~/.julia/packages/Pluto/xIB4x/src/webserver/Static.jl:205
 [12] (::Pluto.var"#246#268"{Bool, Pluto.var"#259#283"{Pluto.ServerSession}, Pluto.ServerSession, Pluto.var"#add_set_secret_cookie!#265"{Pluto.ServerSession}})(request::HTTP.Messages.Request)
    @ Pluto ~/.julia/packages/Pluto/xIB4x/src/webserver/Static.jl:132
 [13] handle(::HTTP.Handlers.RequestHandlerFunction{Pluto.var"#246#268"{Bool, Pluto.var"#259#283"{Pluto.ServerSession}, Pluto.ServerSession, Pluto.var"#add_set_secret_cookie!#265"{Pluto.ServerSession}}}, ::HTTP.Messages.Request)
    @ HTTP.Handlers ~/.julia/packages/HTTP/aTjcj/src/Handlers.jl:254
 [14] handle(::HTTP.Handlers.Router{Symbol("##349")}, ::HTTP.Messages.Request)
    @ HTTP.Handlers ~/.julia/packages/HTTP/aTjcj/src/Handlers.jl:473
 [15] (::Pluto.var"#346#356"{Pluto.ServerSession, HTTP.Handlers.Router{Symbol("##349")}, Base.RefValue{Function}})(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}})
    @ Pluto ~/.julia/packages/Pluto/xIB4x/src/webserver/WebServer.jl:236
 [16] handle
    @ ~/.julia/packages/HTTP/aTjcj/src/Handlers.jl:270 [inlined]
 [17] #4
    @ ~/.julia/packages/HTTP/aTjcj/src/Handlers.jl:351 [inlined]
 [18] macro expansion
    @ ~/.julia/packages/HTTP/aTjcj/src/Servers.jl:415 [inlined]
 [19] (::HTTP.Servers.var"#13#14"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#346#356"{Pluto.ServerSession, HTTP.Handlers.Router{Symbol("##349")}, Base.RefValue{Function}}}}, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, HTTP.Servers.Server{Nothing, Sockets.TCPServer}, HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})()
    @ HTTP.Servers ./task.jl:423